require:
  - 'rubocop-rspec'
  - 'rubocop-rails'

AllCops:
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
    - 'Guardfile'

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
