require:
  - 'rubocop-rspec'
  - 'rubocop-rails'

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
    - 'Guardfile'
    - 'vendor/bundle/**/*'

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 8

Rails/DeprecatedActiveModelErrorsMethods:
  Exclude:
    - 'app/schemas/application_schema.rb'
